x-airflow-env: &airflow-common
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
  _PIP_ADDITIONAL_REQUIREMENTS: "pandas polars apache-airflow-providers-amazon xlrd selenium dbt-snowflake==1.7.0 dbt-core==1.7.0"
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__LOGGING__REMOTE_LOGGING: 'true'
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: 'aws_default'
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: 's3://spain-housing-datalake/airflow-logs'
  AIRFLOW__SECRETS__BACKEND: 'airflow.providers.amazon.aws.secrets.secrets_manager.SecretsManagerBackend'
  AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix": "airflow/connections", "variables_prefix": "airflow/variables"}'
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1

services:

  airflow:
    image: apache/airflow:2.9.2-python3.10
    restart: always
    environment:
      <<: *airflow-common
      AWS_REGION: eu-west-1
      # Snowflake Credentials (Loaded from .env file)
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres

  scheduler:
    image: apache/airflow:2.9.2-python3.10
    restart: always
    environment:
      <<: *airflow-common
      # Snowflake Credentials (Loaded from .env file)
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_WAREHOUSE: ${SNOWFLAKE_WAREHOUSE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
    command: scheduler
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  remote-chromedriver:
    image: selenium/standalone-chrome:latest
    container_name: remote-chromedriver
    networks:
      - default
    ports:
      - "4444:4444"
    shm_size: "2g"
    restart: always
